class Models {
  final String image;
  final String title;
  final String subtitle;
  Models({required this.image, required this.title, required this.subtitle});
}

List<Models> lists = [
  Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
     Models(image: 'https://images.pexels.com/photos/29022983/pexels-photo-29022983/free-photo-of-coffee-and-cake-with-chestnut-decor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
   title: 'Mawda salah ',
    subtitle: 'قابلك الساعة 8 باذن الله'),
];

